@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar

POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
    "make": "bmw",
    "model": "3 series"
}

###
@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###
GET {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###
DELETE {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###
PUT {{endpoint}}/{{newCar}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{
    "make": "bmw",
    "model": "3 series"
}


 